version: "3.9"
networks:
    test:
        driver: bridge
services:
    web1:
        build: 
            context: .
            dockerfile: MasterNode/Dockerfile
        ports:
            - "9091:80"
        links:
            - "web:secondary"
        networks:
            - test
    web:
        build: 
            context: .
            dockerfile: Secondary1/Dockerfile
        ports:
            - "9092:80"
        networks:
            - test
