version: "3.9"
services:
    master:
        build: 
            context: .
            dockerfile: MasterNode/Dockerfile
        ports:
            - "9091:80"
    secondary1:
        build: 
            context: .
            dockerfile: Secondary1/Dockerfile
        ports:
            - "9092:80"
        environment:
          - DELAY=1000
    secondary2:
        build: 
            context: .
            dockerfile: Secondary1/Dockerfile
        environment:
          - DELAY=5000
        ports:
            - "9093:80"
